export const authors = [
    {
        id: '1',
        matacgia: "1",
        tentacgia: 'Lê Trung Dũng',
        hocham: 'PGS',
        hocvi: 'TS',
        cdkh: 'GVC',
        madonvi: '',
        machuyennganh: 'Điện tử',
        manhomncm: '',
        orcid_id: '',
        huongnghiencuu : 'Động lực học và độ bền kết cấu các phương tiện cơ giới',
        email : 'dung@gmail.com',
    },
    {
        id: '2',
        matacgia: "2",
        tentacgia: 'Nguyễn Thế Mạnh',
        hocham: 'PGS',
        hocvi: 'TS',
        cdkh: 'GVC',
        madonvi: '',
        machuyennganh: 'Xe máy',
        manhomncm: '',
        orcid_id: '',
        huongnghiencuu : 'Động lực học và độ bền kết cấu các phương tiện cơ giới',
        email : '',
    },
    {
        id: '3',
        matacgia: "3",
        tentacgia: 'Cù Xuân Phong',
        hocham: 'PGS',
        hocvi: 'TS',
        cdkh: 'GVC',
        madonvi: '',
        machuyennganh: 'Công nghệ thông tin',
        manhomncm: '',
        orcid_id: '',
        huongnghiencuu : 'Động lực học và độ bền kết cấu các phương tiện cơ giới',
        email : '',
    },
    {
        id: '4',
        matacgia: "4",
        tentacgia: 'Phạm Trung Kiên',
        hocham: 'PGS',
        hocvi: '',
        cdkh: '',
        madonvi: '',
        machuyennganh: '',
        manhomncm: '',
        orcid_id: '',
        huongnghiencuu : 'Động lực học và độ bền kết cấu các phương tiện cơ giới',
        email : '',
    },
    {
        id: '5',
        matacgia: "5",
        tentacgia: 'Nguyễn Minh Tân',
        hocham: 'PGS',
        hocvi: '',
        cdkh: 'GVC',
        madonvi: '',
        machuyennganh: 'Điện tử',
        manhomncm: '',
        orcid_id: '',
        huongnghiencuu : 'Chẩn đoán và dự báo tình trạng kỹ thuật xe xích quân sựĐô tin cậy xe xích quân sự',
        email : '',
    }

]